#pragma once
#include "CoreMinimal.h"
#include "ECharacterProgressionRewardTypes.generated.h"

UENUM(BlueprintType)
enum class ECharacterProgressionRewardTypes : uint8 {
    CombatDeckMenu,
    FlowingAtttackGauges,
    Items,
    Stances,
    AttackSlot_FL_2,
    AttackSlot_FL_3,
    AttackSlot_FR_2,
    AttackSlot_FR_3,
    AttackSlot_BL_2,
    AttackSlot_BL_3,
    AttackSlot_BR_2,
    AttackSlot_BR_3,
    Power_1,
    Power_2,
    Power_3,
    Weapon_WarGloves,
    Weapon_Sword,
    CombatDeckSlot_Barehand_2,
    CombatDeckSlot_Barehand_3,
    CombatDeckSlot_WarGloves_2,
    CombatDeckSlot_WarGloves_3,
    CombatDeckSlot_Sword_2,
    CombatDeckSlot_Sword_3,
    FightingStyle_2,
    FightingStyle_3,
    FightingStyle_4,
    School_FightingStyle,
    School_Deck_BareHands,
    School_Deck_WarGloves,
    School_Deck_Sword,
    School_Power_1,
    School_Power_2,
    School_Weapon,
    School_Disciple,
    Absolver,
    Shard_1,
    Shard_2,
    Shard_3,
    Shard_4,
    Shard_5,
    StarterBuild,
    School_Mask,
    FightingStyle_5,
    PVE_Depth1,
    PVE_Depth2,
    CreateSchool,
    Count,
    None,
};

