#pragma once
#include "CoreMinimal.h"
#include "EFightingActionState.generated.h"

UENUM(BlueprintType)
enum class EFightingActionState : uint8 {
    None,
    FreeMove,
    LockMove,
    RushMove,
    Dodge,
    Grab,
    Attack,
    Hit,
    Inventory,
    Equipment,
    Options,
    SpecialAbility,
    Parried,
    Dead,
    Cancel,
    Meditate,
    StanceSelection,
    StanceEdition,
    ScrollAttackPreview,
    HighlightedAttackPreview,
    ScrollQuadrantSwitch,
    HighlightedQuadrantSwitch,
    QuadrantChange,
    AttackDetails,
    WeaponActionFree,
    WeaponActionLock,
    WeaponActionRush,
    Spawn,
    ItemUse,
    EmoteFree,
    EmoteLock,
    FlyMode,
    AltarInteraction,
    AdversarialIntro,
    AdversarialStartCountdown,
    AdversarialPostMatch,
    AdversarialInitialization,
    Down,
    Revive,
    BeingRevived,
    Cinematic,
    Teleport,
    StoreResource,
    SkippableQuadrantChange,
    GatherCutscene,
    DownSpectator,
    Count,
};

